name: era5
channels: 
        - conda-forge
dependencies:
        - python=3.8
        - click
        - pathlib
        - xarray=0.14.1
        - dask
        - netCDF4
        - cdsapi
        - ipykernel